# Default values for HyperFleet API umbrella chart

hyperfleet-api:
  image:
    # make install will substitute this by data coming from terraform
    registry: CHANGE_ME
  database:
    postgresql:
      enabled: true

  auth:
    enableJwt: false

  config:
    adapters:
      required:
        cluster:
          - adapter1
          - adapter2
        nodepool:
          - adapter3
