# Default values for Sentinel (clusters)

hyperfleet-sentinel:
  image:
    # make install will substitute this by data coming from terraform
    registry: CHANGE_ME

  config:
    sentinel:
      name: hyperfleet-sentinel-clusters

    resourceType: clusters
    resourceSelector: []

    debugConfig: false

    log:
      level: info
      format: json
      output: stdout

    clients:
      hyperfleetApi:
        baseUrl: http://hyperfleet-api:8000
        version: v1
        timeout: 10s

  broker:
    type: googlepubsub
    # make install will substitute this by data coming from terraform
    topic: CHANGE_ME
    googlepubsub:
      # make install will substitute this by data coming from terraform
      projectId: CHANGE_ME
    rabbitmq:
      # make install will substitute this by data coming from tf-helm-values.sh
      url: CHANGE_ME
      exchangeType: topic
